"""
VMRC Microsoft Office Power User Training
Instructional Design Curriculum Map & Deployment Playbook
Generated by: Michael Cirigliano, CTT+ | MOUS Master
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ── Color palette ──────────────────────────────────────────────
NAVY        = RGBColor(0x1F, 0x4E, 0x79)
BLUE        = RGBColor(0x2E, 0x75, 0xB6)
LIGHT_BLUE  = RGBColor(0xD6, 0xE4, 0xF0)
ORANGE      = RGBColor(0xC5, 0x5A, 0x11)
GREEN       = RGBColor(0x37, 0x86, 0x4B)
GOLD        = RGBColor(0x7F, 0x60, 0x00)
GRAY        = RGBColor(0x80, 0x80, 0x80)
WHITE       = RGBColor(0xFF, 0xFF, 0xFF)
BLACK       = RGBColor(0x00, 0x00, 0x00)
RED         = RGBColor(0xC0, 0x00, 0x00)

# ── Low-level helpers ───────────────────────────────────────────
def set_cell_bg(cell, hex6):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:fill'), hex6)
    shd.set(qn('w:val'), 'clear')
    tcPr.append(shd)

def set_table_borders(table, color='CCCCCC', sz=4):
    tbl = table._tbl
    tblPr = tbl.tblPr
    tblBorders = OxmlElement('w:tblBorders')
    for side in ('top', 'left', 'bottom', 'right', 'insideH', 'insideV'):
        b = OxmlElement(f'w:{side}')
        b.set(qn('w:val'), 'single')
        b.set(qn('w:sz'), str(sz))
        b.set(qn('w:space'), '0')
        b.set(qn('w:color'), color)
        tblBorders.append(b)
    tblPr.append(tblBorders)

def set_col_widths(table, widths_inches):
    """Set column widths via cell XML for reliability."""
    for row in table.rows:
        for i, cell in enumerate(row.cells):
            if i < len(widths_inches):
                tc = cell._tc
                tcPr = tc.get_or_add_tcPr()
                tcW = OxmlElement('w:tcW')
                twips = str(int(widths_inches[i] * 1440))
                tcW.set(qn('w:w'), twips)
                tcW.set(qn('w:type'), 'dxa')
                # Remove existing tcW if present
                for old in tcPr.findall(qn('w:tcW')):
                    tcPr.remove(old)
                tcPr.append(tcW)

def add_page_number_field(run):
    fldChar1 = OxmlElement('w:fldChar')
    fldChar1.set(qn('w:fldCharType'), 'begin')
    instrText = OxmlElement('w:instrText')
    instrText.text = 'PAGE'
    fldChar2 = OxmlElement('w:fldChar')
    fldChar2.set(qn('w:fldCharType'), 'end')
    run._r.append(fldChar1)
    run._r.append(instrText)
    run._r.append(fldChar2)

def heading(doc, text, level=1, color=NAVY, pt_before=12, pt_after=6):
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(pt_before)
    p.paragraph_format.space_after  = Pt(pt_after)
    # Apply heading style
    p.style = doc.styles[f'Heading {level}']
    if p.runs:
        run = p.runs[0]
    else:
        run = p.add_run(text)
    run.text = text
    run.font.color.rgb = color
    return p

def para(doc, text, bold=False, italic=False, color=None, size=11,
         indent=0, pt_before=0, pt_after=6, align=None):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    if color:
        run.font.color.rgb = color
    if indent:
        p.paragraph_format.left_indent = Inches(indent)
    p.paragraph_format.space_before = Pt(pt_before)
    p.paragraph_format.space_after  = Pt(pt_after)
    if align:
        p.alignment = align
    return p

def bullet(doc, text, bold_prefix=None, indent=0.3, size=10):
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.left_indent = Inches(indent)
    p.paragraph_format.space_after  = Pt(3)
    if bold_prefix:
        r1 = p.add_run(bold_prefix)
        r1.font.bold = True
        r1.font.size = Pt(size)
        r2 = p.add_run(text)
        r2.font.size = Pt(size)
    else:
        r = p.add_run(text)
        r.font.size = Pt(size)
    return p

def spacer(doc, pt=6):
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(pt)

def banner_row(table, row_idx, text, bg_hex, text_color=WHITE, size=10, merge_to=None):
    row = table.rows[row_idx]
    cell = row.cells[0]
    if merge_to is not None:
        cell = cell.merge(row.cells[merge_to])
    set_cell_bg(cell, bg_hex)
    p = cell.paragraphs[0]
    run = p.add_run(text)
    run.font.bold = True
    run.font.color.rgb = text_color
    run.font.size = Pt(size)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    return cell

def header_cell(cell, text, bg_hex, size=9):
    set_cell_bg(cell, bg_hex)
    p = cell.paragraphs[0]
    run = p.add_run(text)
    run.font.bold = True
    run.font.color.rgb = WHITE
    run.font.size = Pt(size)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

def data_cell(cell, text, bg_hex='FFFFFF', bold=False, size=9,
              color=None, center=False):
    set_cell_bg(cell, bg_hex)
    p = cell.paragraphs[0]
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.font.bold = bold
    if color:
        run.font.color.rgb = color
    if center:
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

def add_module_block(doc, mod_id, title, duration, fmt, audience,
                     scenario, skills, deliverable):
    track_colors = {'W': '2E75B6', 'E': '37864B', 'P': 'C55A11'}
    bg = track_colors.get(mod_id[0], '595959')

    # Title bar
    t = doc.add_table(rows=1, cols=1)
    set_col_widths(t, [6.75])
    cell = t.rows[0].cells[0]
    set_cell_bg(cell, bg)
    p = cell.paragraphs[0]
    run = p.add_run(f'{mod_id}  |  {title}')
    run.font.bold = True
    run.font.color.rgb = WHITE
    run.font.size = Pt(12)

    # Meta
    mp = doc.add_paragraph()
    mp.paragraph_format.left_indent = Inches(0.2)
    mp.paragraph_format.space_after = Pt(3)
    for lbl, val, sep in [('Duration:', duration, '   |   '),
                           ('Format:', fmt, '   |   '),
                           ('Audience:', audience, '')]:
        r = mp.add_run(lbl)
        r.font.bold = True; r.font.size = Pt(10)
        r2 = mp.add_run(f' {val}')
        r2.font.size = Pt(10)
        if sep:
            r3 = mp.add_run(sep)
            r3.font.color.rgb = GRAY; r3.font.size = Pt(10)

    # Scenario
    sp = doc.add_paragraph()
    sp.paragraph_format.left_indent = Inches(0.2)
    sp.paragraph_format.space_after = Pt(3)
    r = sp.add_run('Scenario: ')
    r.font.bold = True; r.font.italic = True
    r.font.color.rgb = NAVY; r.font.size = Pt(10)
    r2 = sp.add_run(scenario)
    r2.font.italic = True; r2.font.size = Pt(10)

    # Skills
    hp = doc.add_paragraph()
    hp.paragraph_format.left_indent = Inches(0.2)
    hp.paragraph_format.space_after = Pt(2)
    r = hp.add_run('Key Skills Covered:')
    r.font.bold = True; r.font.size = Pt(10)
    for sk in skills:
        bullet(doc, sk, indent=0.5, size=10)

    # Deliverable
    dp = doc.add_paragraph()
    dp.paragraph_format.left_indent = Inches(0.2)
    dp.paragraph_format.space_after = Pt(10)
    r = dp.add_run('Module Deliverable: ')
    r.font.bold = True
    r.font.color.rgb = ORANGE; r.font.size = Pt(10)
    r2 = dp.add_run(deliverable)
    r2.font.size = Pt(10)

# ══════════════════════════════════════════════════════════════
# BUILD DOCUMENT
# ══════════════════════════════════════════════════════════════
doc = Document()

# Page setup
for sec in doc.sections:
    sec.top_margin    = Inches(1.0)
    sec.bottom_margin = Inches(1.0)
    sec.left_margin   = Inches(1.25)
    sec.right_margin  = Inches(1.25)

# Default font
doc.styles['Normal'].font.name = 'Calibri'
doc.styles['Normal'].font.size = Pt(11)

# ──────────────────────────────────────────────────────────────
# COVER PAGE
# ──────────────────────────────────────────────────────────────
p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
p.paragraph_format.space_before = Pt(48)
run = p.add_run('VIRGINIA MENNONITE RETIREMENT COMMUNITY')
run.font.size = Pt(13); run.font.bold = True; run.font.color.rgb = NAVY

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('Microsoft Office Power User Training Program')
run.font.size = Pt(26); run.font.bold = True; run.font.color.rgb = NAVY
p.paragraph_format.space_before = Pt(12); p.paragraph_format.space_after = Pt(6)

p = doc.add_paragraph()
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('Instructional Design Curriculum Map & Deployment Playbook')
run.font.size = Pt(14); run.font.italic = True; run.font.color.rgb = BLUE
p.paragraph_format.space_after = Pt(18)

# Rule line using paragraph border
p = doc.add_paragraph()
pPr = p._p.get_or_add_pPr()
pBdr = OxmlElement('w:pBdr')
bot = OxmlElement('w:bottom')
bot.set(qn('w:val'), 'single'); bot.set(qn('w:sz'), '12')
bot.set(qn('w:space'), '1'); bot.set(qn('w:color'), '1F4E79')
pBdr.append(bot); pPr.append(pBdr)
p.paragraph_format.space_after = Pt(20)

# Meta info table
meta = doc.add_table(rows=5, cols=2)
meta.alignment = WD_TABLE_ALIGNMENT.CENTER
set_col_widths(meta, [1.5, 5.0])
set_table_borders(meta, 'D6E4F0', sz=6)

meta_rows = [
    ('Prepared by:',   'Michael Cirigliano, CTT+  |  MOUS Master  |  IT Applications Administrator'),
    ('Directed by:',   'Director of IT Operations / Human Resources'),
    ('Organization:',  'Virginia Mennonite Retirement Community (VMRC)  |  Harrisonburg, VA'),
    ('Date Issued:',   'January 2026'),
    ('Document Type:', 'Instructional Design Curriculum Map — Internal Training Initiative'),
]
for i, (lbl, val) in enumerate(meta_rows):
    r = meta.rows[i]
    set_cell_bg(r.cells[0], 'D6E4F0')
    set_cell_bg(r.cells[1], 'F8FBFE')
    p = r.cells[0].paragraphs[0]
    p.paragraph_format.left_indent = Inches(0.1)
    rn = p.add_run(lbl); rn.font.bold = True; rn.font.color.rgb = NAVY; rn.font.size = Pt(10)
    p2 = r.cells[1].paragraphs[0]
    p2.paragraph_format.left_indent = Inches(0.1)
    rn2 = p2.add_run(val); rn2.font.size = Pt(10)

spacer(doc, 20)

para(doc, 'What This Document Delivers', bold=True, size=13,
     color=ORANGE, pt_before=0, pt_after=6,
     align=WD_ALIGN_PARAGRAPH.CENTER)

cover_points = [
    'Role-differentiated blended learning across Word, Excel, and PowerPoint',
    'Complete ID Map — 12 modules with objectives, scenarios, and time estimates',
    'Phased rollout strategy with evidence-based deployment timing',
    'Assessment design, Kirkpatrick evaluation framework, and Power User certification path',
    'Job aid templates and LMS delivery architecture recommendation',
]
for pt in cover_points:
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(4)
    run = p.add_run(f'  ▦   {pt}')
    run.font.size = Pt(10); run.font.color.rgb = RGBColor(0x40, 0x40, 0x40)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# DIRECTIVE MEMO
# ──────────────────────────────────────────────────────────────
p = doc.add_paragraph()
r = p.add_run('INTERNAL TRAINING DIRECTIVE')
r.font.size = Pt(9); r.font.bold = True; r.font.color.rgb = GRAY; r.font.all_caps = True
p.paragraph_format.space_after = Pt(4)

heading(doc, 'Memorandum: Microsoft Office Power User Training Initiative', level=1)

memo_t = doc.add_table(rows=4, cols=2)
set_col_widths(memo_t, [1.0, 5.75])
set_table_borders(memo_t, 'E7E7E7', sz=4)
memo_data = [
    ('TO:',   'Michael Cirigliano, IT Applications Administrator'),
    ('FROM:', 'IT Director / Vice President of Operations, VMRC'),
    ('DATE:', 'January 2026'),
    ('RE:',   'Design & Deployment of Microsoft Office Power User Training Curriculum'),
]
for i, (lbl, val) in enumerate(memo_data):
    row = memo_t.rows[i]
    set_cell_bg(row.cells[0], 'F2F2F2')
    p1 = row.cells[0].paragraphs[0]
    r1 = p1.add_run(lbl); r1.font.bold = True; r1.font.size = Pt(10)
    p2 = row.cells[1].paragraphs[0]
    r2 = p2.add_run(val); r2.font.size = Pt(10)

spacer(doc, 8)
para(doc, (
    'VMRC has identified a significant gap in Microsoft Office proficiency across clinical and administrative '
    'staff. Inconsistent document formatting, manual processes that should be automated, and repeated helpdesk '
    'requests for basic Office tasks are reducing productivity and increasing documentation risk under our HIPAA '
    'obligations. Resident care documentation quality—particularly in Word-based care plans and Excel-based '
    'census and staffing reports—needs to be standardized and improved.'
), pt_after=10)

para(doc, 'You are directed to:', bold=True, pt_after=4)
for d in [
    'Conduct a learner needs analysis across nursing and administrative staff populations',
    'Design a competency-based curriculum covering Word, Excel, and PowerPoint',
    'Identify and develop a Power User cohort who will serve as internal technology champions',
    'Produce all training materials, assessments, and a deployment playbook',
    'Execute a phased rollout that minimizes disruption to patient care operations',
]:
    bullet(doc, d)

spacer(doc, 8)
para(doc, 'This document is your formal response to that directive.',
     bold=True, italic=True, color=NAVY, pt_after=20)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 1: LEARNER ANALYSIS
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 1: Learner Analysis & Needs Assessment', level=1)

heading(doc, '1.1  Why This Matters in a Retirement Community', level=2)
para(doc, (
    'VMRC is not a standard corporate environment. It is a 24/7 care operation where Word documents are '
    'resident care plans, Excel spreadsheets are staffing grids and census reports, and PowerPoint '
    'presentations go before family members, state surveyors, and the board. Every poorly formatted '
    'document carries real operational and regulatory risk. Every hour a nurse spends reformatting a '
    'template is an hour not at bedside. This training is not about abstract productivity—it is about '
    'care quality and organizational compliance.'
), pt_after=10)

heading(doc, '1.2  Audience Profiles', level=2)
aud = doc.add_table(rows=6, cols=5)
aud.alignment = WD_TABLE_ALIGNMENT.LEFT
set_col_widths(aud, [1.5, 1.1, 1.1, 1.6, 1.45])
set_table_borders(aud, '2E75B6', sz=4)

for i, h in enumerate(['Role Group', 'Tech Comfort', 'Shift Pattern',
                        'Primary Office Need', 'Available Format']):
    header_cell(aud.rows[0].cells[i], h, '1F4E79', size=9)

aud_rows = [
    ('RN / LPN (Charge Nurses)', 'Low–Medium', '12-hr rotating', 'Word: care plans\nExcel: staffing', '20-min LMS modules'),
    ('CNA / Med Aide',           'Low',         '8–12 hr shifts', 'Word: basic forms',                '10-min micro-modules'),
    ('Administrative Staff',     'Medium–High', 'M–F, 8–5',       'All three apps',                   '60-min workshops'),
    ('Dept Heads / DON',         'Medium',      'M–F + on-call',  'Excel dashboards\nPPT reports',    'Blended'),
    ('Power User Cohort',        'High',        'Mixed',          'Advanced all three',               'Dedicated sessions'),
]
stripes = ['F8FBFE', 'EEF4FA']
for ri, row_d in enumerate(aud_rows):
    row = aud.rows[ri + 1]
    bg = stripes[ri % 2]
    for ci, txt in enumerate(row_d):
        data_cell(row.cells[ci], txt, bg, bold=(ci == 0), size=9)

spacer(doc, 10)
heading(doc, '1.3  Gap Analysis', level=2)
gap = doc.add_table(rows=5, cols=3)
set_col_widths(gap, [2.0, 2.0, 2.75])
set_table_borders(gap, '2E75B6', sz=4)

for i, h in enumerate(['Current State', 'Desired State (Post-Training)', 'The Gap']):
    header_cell(gap.rows[0].cells[i], h, '2E75B6', size=9)

gap_rows = [
    ('Staff manually reformat documents each time',
     'Templates and styles applied consistently',
     'No template library; no styles training'),
    ('Excel used only for basic lists',
     'Pivot tables, VLOOKUP, census dashboards',
     'No formula or data analysis training'),
    ('Presentations inconsistent, unbranded',
     'Branded, data-driven slide decks',
     'No PPT standards or master-slide training'),
    ('Helpdesk tickets for basic formatting questions',
     'Self-sufficient staff plus internal coaches',
     'No Power User structure; no skill tiers'),
]
for ri, row_d in enumerate(gap_rows):
    row = gap.rows[ri + 1]
    bg = stripes[ri % 2]
    for ci, txt in enumerate(row_d):
        data_cell(row.cells[ci], txt, bg, size=9)

spacer(doc, 10)
heading(doc, '1.4  HIPAA Training Compliance Note', level=2)

# Warning box
wb = doc.add_table(rows=1, cols=1)
set_col_widths(wb, [6.75])
set_table_borders(wb, 'FFD700', sz=6)
cell = wb.rows[0].cells[0]
set_cell_bg(cell, 'FFF2CC')
p = cell.paragraphs[0]
p.paragraph_format.left_indent  = Inches(0.1)
p.paragraph_format.space_before = Pt(4)
p.paragraph_format.space_after  = Pt(4)
r1 = p.add_run('⚠  HIPAA Note: ')
r1.font.bold = True; r1.font.color.rgb = GOLD; r1.font.size = Pt(10)
r2 = p.add_run(
    'All training materials use fully de-identified dummy data. No actual resident names, '
    'MRNs, diagnosis codes, or PII appear anywhere in this curriculum. Examples use '
    '"Resident A / B / C" conventions. This is a non-negotiable design constraint. '
    'Confirm with your Privacy Officer that training devices meet BAA and HIPAA Security Rule requirements.'
)
r2.font.size = Pt(10)

spacer(doc, 8)
doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 2: THE ID MAP
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 2: The ID Map — Curriculum Architecture', level=1)

heading(doc, '2.1  What Is an ID Map?', level=2)
para(doc, (
    'An Instructional Design (ID) Map is the master blueprint of a training program. It answers four '
    'questions simultaneously: Who learns what? In what order? How is it delivered? How is mastery '
    'verified? Unlike a list of topics, an ID Map makes logical dependencies visible, assigns time '
    'and format to each element, and maps content to specific roles. In a retirement community context '
    'this is essential: you cannot pull all staff off the floor at once, roles need different content, '
    'and clinical staff need radically efficient formats.'
), pt_after=10)

heading(doc, '2.2  Three-Track Architecture', level=2)
para(doc, (
    'This curriculum uses three parallel application tracks (Word, Excel, PowerPoint) built on a shared '
    'Foundation layer, with a Power User Certification capstone. Each track has four progressive modules. '
    'Role assignments determine which tracks each staff group completes.'
), pt_after=10)

# Architecture / ID Map table — 6 rows x 5 cols
arch = doc.add_table(rows=7, cols=5)
set_col_widths(arch, [1.55, 1.55, 1.55, 1.5, 0.6])
set_table_borders(arch, '2E75B6', sz=4)

# Row 0: Foundation banner (merge cols 0-3)
r0 = arch.rows[0]
merged = r0.cells[0].merge(r0.cells[3])
set_cell_bg(merged, '1F4E79')
p = merged.paragraphs[0]
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run('FOUNDATION LAYER — Microsoft 365 Orientation  ●  All Staff  ●  30 min  ●  Asynchronous')
run.font.bold = True; run.font.color.rgb = WHITE; run.font.size = Pt(10)
header_cell(r0.cells[4], 'Min', '1F4E79', size=9)

# Row 1: Track headers
track_hdr_data = [
    ('TRACK W: WORD',        '2E75B6'),
    ('TRACK E: EXCEL',       '37864B'),
    ('TRACK P: POWERPOINT',  'C55A11'),
    ('ROLE ASSIGNMENT',      '595959'),
    ('MIN',                  '595959'),
]
for ci, (txt, bg) in enumerate(track_hdr_data):
    header_cell(arch.rows[1].cells[ci], txt, bg, size=9)

# Rows 2–5: Modules
modules_map = [
    ('W1: Document Architecture\n& Templates',          'D6E4F0',
     'E1: Clean Data Entry\n& Structure',               'E2EFDA',
     'P1: Slide Design\nPrinciples',                    'FCE4D6',
     'Admin + All Nurses',   'F2F2F2',  '30'),
    ('W2: Styles, Formatting\n& Professional Docs',     'BDD7EE',
     'E2: Essential Functions\n(IF, VLOOKUP, SUMIF)',   'CEECC3',
     'P2: Master Slides\n& Brand Templates',            'F8CBAD',
     'Admin + Charge RNs',   'EBEBEB',  '45'),
    ('W3: Collaborative Review\n(Track Changes)',       'A9C4E1',
     'E3: Pivot Tables\nfor Census & Staffing',         'B6E0B6',
     'P3: Data Visualization\n(Link Excel Data)',       'F4B183',
     'Admin + Dept Heads',   'F2F2F2',  '45'),
    ('W4: Mail Merge\n& Automation',                    '89B1D3',
     'E4: Dashboard Building\n& Visual Reporting',      '9DD1A8',
     'P4: Executive &\nFamily Presentations',           'F0925A',
     'Power Users Only',     'FFF2CC',  '60'),
]
for ri, row_d in enumerate(modules_map):
    row = arch.rows[ri + 2]
    for ci, (txt, bg) in enumerate(zip(row_d[::2], row_d[1::2])):
        data_cell(row.cells[ci], txt, bg, size=9,
                  bold=(ci == 3 and ri == 3),
                  center=(ci == 4))

# Row 6: Capstone banner
r6 = arch.rows[6]
cap_merged = r6.cells[0].merge(r6.cells[3])
set_cell_bg(cap_merged, '7F6000')
p = cap_merged.paragraphs[0]
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = p.add_run(
    'POWER USER CAPSTONE — Competency Demo + Train-the-Trainer Certification  '
    '●  All 3 Tracks Required'
)
run.font.bold = True; run.font.color.rgb = WHITE; run.font.size = Pt(10)
set_cell_bg(r6.cells[4], '7F6000')
p4 = r6.cells[4].paragraphs[0]
p4.alignment = WD_ALIGN_PARAGRAPH.CENTER
run4 = p4.add_run('4 hr')
run4.font.bold = True; run4.font.color.rgb = WHITE; run4.font.size = Pt(9)

spacer(doc, 12)
heading(doc, '2.3  Role Assignment Matrix', level=2)

role_tbl = doc.add_table(rows=6, cols=5)
set_col_widths(role_tbl, [1.8, 1.2, 1.2, 1.2, 1.35])
set_table_borders(role_tbl, '2E75B6', sz=4)
for i, h in enumerate(['Staff Role', 'Word Track', 'Excel Track', 'PPT Track', 'Power User Eligible']):
    header_cell(role_tbl.rows[0].cells[i], h, '1F4E79', size=9)

role_matrix = [
    ('CNA / Med Aide',           'W1 only',  '—',   '—',   'No'),
    ('RN / LPN (Charge)',        'W1–W3', 'E1–E2', '—', 'By application'),
    ('Administrative Staff',     'W1–W4', 'E1–E3', 'P1–P3', 'Yes'),
    ('Department Head / DON',    'W1–W3', 'E1–E4', 'P1–P4', 'Yes'),
    ('Power User Cohort',        'W1–W4', 'E1–E4', 'P1–P4', 'Required'),
]
for ri, row_d in enumerate(role_matrix):
    row = role_tbl.rows[ri + 1]
    bg = stripes[ri % 2]
    for ci, txt in enumerate(row_d):
        is_yes = txt in ('Yes', 'Required')
        is_no  = txt == 'No'
        data_cell(row.cells[ci], txt, bg, bold=(ci == 0 or is_yes),
                  size=9,
                  color=GREEN if is_yes else (GRAY if is_no else None))

spacer(doc, 8)
doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 3: LEARNING OBJECTIVES
# ──────────────────────────────────────────────────────────────
heading(doc, "Section 3: Learning Objectives (Bloom’s Taxonomy Aligned)", level=1)
para(doc, (
    "All objectives are written at the appropriate Bloom’s Taxonomy cognitive level. "
    "Foundation and Module 1 objectives target Remember/Understand. Modules 2–3 target Apply/Analyze. "
    "Module 4 and the Power User Capstone reach Evaluate and Create—the highest cognitive tiers."
), pt_after=10)

tracks_objs = [
    ('Track W: Microsoft Word', BLUE, '2E75B6', [
        ('W1', 'Remember / Understand',
         'Apply document styles, heading hierarchies, and pre-built templates to create consistently formatted documents.'),
        ('W2', 'Apply',
         'Construct professional documents using section breaks, headers/footers, table of contents, and formatting controls.'),
        ('W3', 'Analyze / Apply',
         'Demonstrate collaborative review by applying track changes, resolving conflicts, and managing multi-author edits.'),
        ('W4', 'Create',
         'Build mail merge workflows and Quick Parts automation to produce repeatable documents at scale.'),
    ]),
    ('Track E: Microsoft Excel', GREEN, '37864B', [
        ('E1', 'Remember / Understand',
         'Structure data correctly in a flat-file format, apply data validation, and use named ranges for organized spreadsheets.'),
        ('E2', 'Apply',
         'Construct formulas using IF, VLOOKUP, SUMIF, and COUNTIF to answer operational questions about census and staffing.'),
        ('E3', 'Analyze',
         'Build and interpret pivot tables that summarize resident census, staffing ratios, and cost data by date, unit, and category.'),
        ('E4', 'Create / Evaluate',
         'Design operational dashboards combining charts, slicers, and conditional formatting to deliver decision-ready KPI reporting.'),
    ]),
    ('Track P: Microsoft PowerPoint', ORANGE, 'C55A11', [
        ('P1', 'Remember / Understand',
         'Apply the four core design principles (Contrast, Alignment, Proximity, Repetition) to evaluate and improve slide quality.'),
        ('P2', 'Apply',
         'Modify master slides and slide layouts to establish and maintain VMRC brand standards across all presentations.'),
        ('P3', 'Analyze / Apply',
         'Link live Excel data to PowerPoint charts so presentations auto-update when source data changes.'),
        ('P4', 'Create',
         'Design and deliver a professional presentation for a family communication or leadership reporting scenario.'),
    ]),
]

for track_name, track_color, bg_hex, objs in tracks_objs:
    heading(doc, track_name, level=2, color=track_color)
    ot = doc.add_table(rows=len(objs) + 1, cols=3)
    set_col_widths(ot, [0.6, 1.5, 4.65])
    set_table_borders(ot, 'CCCCCC', sz=4)
    for i, h in enumerate(['Mod', "Bloom’s Level", 'By End of Module, Learner Will Be Able To…']):
        header_cell(ot.rows[0].cells[i], h, bg_hex, size=9)
    for ri, (mod, bloom, obj) in enumerate(objs):
        row = ot.rows[ri + 1]
        bg = 'F8F8F8' if ri % 2 == 0 else 'FFFFFF'
        data_cell(row.cells[0], mod,   bg, bold=True, size=9)
        data_cell(row.cells[1], bloom, bg, size=9)
        data_cell(row.cells[2], obj,   bg, size=9)
    spacer(doc, 8)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 4: MODULE DESIGNS
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 4: Module-by-Module Design', level=1)
para(doc, (
    'Each module describes the instructional content, format, duration, and hands-on deliverable. '
    'All scenarios are drawn from retirement community operations to ensure immediate relevance and '
    'on-the-job transfer. Modules are sequenced by prerequisite: complete in order within each track.'
), pt_after=10)

heading(doc, 'Track W: Microsoft Word', level=2, color=BLUE)

add_module_block(doc,
    'W1', 'Document Architecture & Templates', '30 min', 'Self-paced LMS module',
    'All staff who use Word',
    '"Every time I open a new care plan I have to fix the margins, change the font, and redo the heading. There has to be a better way."',
    [
        'Opening and saving from VMRC document templates (.dotx)',
        'Understanding the Normal style vs. Heading 1 / 2 / 3 styles',
        'Applying pre-built document themes',
        'Setting default font, margins, and line spacing',
        'Using the Styles pane to maintain consistency across documents',
    ],
    'Learner reformats a provided messy care plan using only the Styles pane—zero manual formatting.')

add_module_block(doc,
    'W2', 'Styles, Formatting & Professional Documents', '45 min',
    'Self-paced + 15-min live Q&A session',
    'Administrative staff, Charge RNs',
    '"The nursing handbook gets updated quarterly but it looks different every time depending on who edited it last."',
    [
        'Creating and modifying custom paragraph and character styles',
        'Building an automatic Table of Contents from Heading styles',
        'Inserting and formatting headers and footers with page numbers',
        'Section breaks for different formatting within one document',
        'Find & Replace with formatting options',
    ],
    'Learner produces a 3-section formatted policy document with auto-TOC, consistent styles, and a page-numbered footer.')

add_module_block(doc,
    'W3', 'Collaborative Review & Track Changes', '30 min',
    'Self-paced LMS module',
    'All staff who co-author documents',
    '"Three people edited the fall prevention policy and now no one knows what changed."',
    [
        'Turning Track Changes on/off and setting author identity',
        'Accepting, rejecting, and navigating tracked changes',
        'Adding and resolving comments',
        'Using Compare Documents for version control',
        'Setting document permissions and protecting sections',
    ],
    'Learner reviews a redlined policy document, accepts/rejects changes, resolves all comments, and produces a clean final copy.')

add_module_block(doc,
    'W4', 'Mail Merge & Automation', '45 min',
    'Instructor-led workshop (hands-on lab)',
    'Administrative staff, Power Users',
    '"Every month I spend two hours manually filling the same resident information into individual family communication letters."',
    [
        'Mail merge from an Excel data source to a Word letter template',
        'Filtering merge records (e.g., residents on Unit 2 only)',
        'Creating merge rules (IF/THEN for personalized content)',
        'Quick Parts and AutoText for repeated content blocks',
        'Running and reviewing a full merge batch',
    ],
    'Learner produces 20 personalized monthly communication letters from a dummy resident list in under 5 minutes.')

heading(doc, 'Track E: Microsoft Excel', level=2, color=GREEN)

add_module_block(doc,
    'E1', 'Clean Data Entry & Structure', '30 min',
    'Self-paced LMS module',
    'All Excel users',
    '"Our census spreadsheet has data in random columns, merged cells everywhere, and the formulas break whenever someone adds a row."',
    [
        'Flat-file data structure principles (one row = one record)',
        'Data types: numbers, text, dates—and why they matter',
        'Data validation (dropdowns, date constraints, numeric limits)',
        'Removing merged cells and restructuring for analysis',
        'Named ranges for readable, maintainable formulas',
    ],
    'Learner restructures a messy 50-row dummy census sheet into a clean, validation-protected flat-file table.')

add_module_block(doc,
    'E2', 'Essential Functions: IF, VLOOKUP, SUMIF', '45 min',
    'Self-paced LMS + practice file',
    'Administrative staff, Charge RNs',
    '"I need to know how many residents are on the Medicare A benefit this week without counting by hand."',
    [
        'IF statements for conditional logic (status flags, acuity alerts)',
        'VLOOKUP and XLOOKUP for cross-referencing roster data',
        'SUMIF and COUNTIF for aggregating by category',
        'IFERROR to suppress error display in shared spreadsheets',
        'Nesting functions (combining IF with VLOOKUP)',
    ],
    'Learner builds a formula-driven staffing summary that auto-calculates census by wing, payor type, and acuity level.')

add_module_block(doc,
    'E3', 'Pivot Tables for Census & Staffing Analysis', '60 min',
    'Instructor-led workshop',
    'Administrative staff, Department Heads',
    '"The DON wants a weekly census breakdown by wing, level of care, and payor—and she needs it by Monday morning."',
    [
        'Creating pivot tables from flat-file data sources',
        'Row / column / filter / value field placement',
        'Grouping dates by week, month, and quarter',
        'Pivot charts for visual summaries',
        'Slicers for interactive, presentation-ready filtering',
        'Refreshing pivot tables when source data updates',
    ],
    'Learner builds a complete weekly census pivot report with slicers for unit, payor, and date—reusable every week.')

add_module_block(doc,
    'E4', 'Dashboard Building & Visual Reporting', '60 min',
    'Power User workshop (lab)',
    'Power Users, Department Heads',
    '"Leadership wants a one-page dashboard for the weekly stand-up showing census, staffing ratios, and open incidents at a glance."',
    [
        'Dashboard layout design (one sheet = one story)',
        'Conditional formatting for KPI traffic lights (red / yellow / green)',
        'Sparklines and mini-charts for trend visibility',
        'Dynamic chart ranges using Excel Tables (auto-expanding)',
        'Linking charts to a summary dashboard from source-data sheets',
        'Protecting dashboard cells while allowing slicer interaction',
    ],
    'Learner builds a 1-page operations dashboard with 5 live KPIs, color-coded alerts, and a weekly trend chart—for a fictional SNF unit.')

heading(doc, 'Track P: Microsoft PowerPoint', level=2, color=ORANGE)

add_module_block(doc,
    'P1', 'Slide Design Principles', '30 min',
    'Self-paced LMS module',
    'All PowerPoint users',
    '"Our staff meeting slides have 12-point text in paragraph form and every slide is a different color."',
    [
        'The four design principles: Contrast, Alignment, Proximity, Repetition (CARP)',
        'Font hierarchy: title, body, and caption sizing rules',
        'Color theory basics: 3-color rule, contrast ratios for accessibility',
        'One idea per slide—information architecture for presentations',
        'Before/after slide critique exercise',
    ],
    'Learner audits a provided 10-slide "bad" deck using a design checklist and produces a written critique with specific improvement recommendations.')

add_module_block(doc,
    'P2', 'Master Slides & Brand Templates', '30 min',
    'Instructor-led workshop',
    'Administrative staff, Power Users',
    '"Every department uses different fonts and colors. Can we just have one VMRC template everyone uses?"',
    [
        'Accessing and editing Slide Master view',
        'Setting fonts, colors, and logo placement in the master',
        'Creating slide layouts for different content types (title, content, data)',
        'Saving as a .potx template file for organization-wide deployment',
        'Distributing and enforcing template use across departments',
    ],
    'Learner creates a VMRC-branded 4-layout slide template (.potx) with correct fonts, colors, and a logo placeholder.')

add_module_block(doc,
    'P3', 'Data Visualization & Linking Excel', '45 min',
    'Self-paced LMS + practice file',
    'Administrative staff, Department Heads',
    '"Our census chart in the board presentation is always out of date because someone has to manually update it."',
    [
        'Choosing the right chart type (bar vs. line vs. pie—and when not to use pie)',
        'Paste Special: linking vs. embedding Excel charts in PowerPoint',
        'Updating linked data and breaking links when needed',
        'SmartArt for process flows and org charts',
        'Accessibility: alt text and readable contrast ratios',
    ],
    'Learner inserts a live-linked Excel census chart into a slide and verifies it updates when source data changes.')

add_module_block(doc,
    'P4', 'Executive & Family Communication Presentations', '45 min',
    'Instructor-led workshop',
    'Department Heads, Power Users',
    '"We have a family night next month and the administrator wants a polished presentation, not the usual slide dump."',
    [
        'Storytelling structure (Context → Complication → Resolution)',
        'Designing a 10-slide executive briefing deck',
        'Resident/family-facing communication: warm, accessible, non-clinical tone',
        'Presenter view, speaker notes, and remote-clicker workflow',
        'Exporting to PDF for distribution without editable versions',
    ],
    'Learner designs and delivers a 5-minute mock “Family Night” deck for a fictional memory care unit.')

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 5: DELIVERY STRATEGY
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 5: Delivery Strategy', level=1)

heading(doc, '5.1  Blended Learning Model', level=2)
para(doc, (
    'This curriculum uses a blended model: short asynchronous modules (LMS-delivered) for knowledge '
    'transfer, and instructor-led workshops for skill application and collaborative practice. The ratio '
    'is approximately 60% asynchronous / 40% synchronous. This is specifically chosen for the '
    'retirement community context where pulling clinical staff off the floor for extended periods is '
    'operationally costly and often impractical.'
), pt_after=10)

del_t = doc.add_table(rows=5, cols=4)
set_col_widths(del_t, [1.5, 1.2, 2.3, 1.75])
set_table_borders(del_t, '2E75B6', sz=4)
for i, h in enumerate(['Format', 'Duration', 'When Used', 'Audience']):
    header_cell(del_t.rows[0].cells[i], h, '2E75B6', size=9)
del_rows = [
    ('LMS Module\n(Asynchronous)',        '15–30 min',  'W1, W3, E1, E2, P1',       'All staff—self-paced, any device'),
    ('Instructor-Led Workshop',           '60–90 min',  'W2, W4, E3, E4, P2, P4',   'Groups of 8–12 in computer lab'),
    ('Job Aid / Laminated Quick Card',    'Reference',       'Post-module support',        'All staff—posted at workstations'),
    ('Power User Capstone Session',       '4 hours',         'End of all 3 tracks',       'Power User cohort only'),
]
for ri, row_d in enumerate(del_rows):
    row = del_t.rows[ri + 1]
    bg = stripes[ri % 2]
    for ci, txt in enumerate(row_d):
        data_cell(row.cells[ci], txt, bg, size=9)

spacer(doc, 10)
heading(doc, '5.2  Shift-Based Scheduling Rules', level=2)
for rule in [
    'Never remove clinical staff from the floor during peak care hours (7–9 AM, 11 AM–1 PM, 5–7 PM). Schedule workshops during mid-shift overlap windows (9–11 AM, 2–4 PM).',
    'All asynchronous modules must be completable on mobile devices. Charge nurses may complete them at the nursing station between resident interactions.',
    'Workshop groups must be role-homogeneous: do not mix CNAs with administrators. Pace and relevance differ significantly.',
    'Offer each workshop in at least two time slots to accommodate rotating shift patterns.',
]:
    bullet(doc, rule)

spacer(doc, 10)
heading(doc, '5.3  LMS Architecture (LearnWorlds / SCORM-Compliant)', level=2)
para(doc, (
    'One LMS course per track (three courses total). Modules are sequential within each course: '
    'completion unlocks next module. Manager dashboard shows direct-report completion status. '
    'Track certificates feed Power User eligibility tracking. Compliance reporting exports to '
    'VMRC HR system. All modules include closed-caption transcripts and pass/fail activity scores '
    'stored in the LMS gradebook.'
), pt_after=10)

heading(doc, '5.4  Job Aids Strategy', level=2)
para(doc, (
    'Every module produces one laminated quick reference card (8.5" × 5.5" half-sheet). Cards are '
    'posted at clinical workstations and administrative desks. Cards use color-coded borders matching '
    'track colors (Word = blue, Excel = green, PowerPoint = orange). Job aids are performance support '
    'tools—they reinforce training, they do not replace it.'
), pt_after=8)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 6: ASSESSMENT PLAN
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 6: Assessment Plan', level=1)
para(doc, (
    'This curriculum uses a three-layer assessment approach: pre-assessment to establish baselines, '
    'formative assessments within modules, and summative performance demonstrations at completion. '
    'Assessment philosophy: measure what learners can DO, not what they can recall. Multiple-choice '
    'questions are used sparingly and only to confirm conceptual understanding before practice tasks.'
), pt_after=10)

ass_t = doc.add_table(rows=5, cols=4)
set_col_widths(ass_t, [1.5, 1.3, 2.5, 1.45])
set_table_borders(ass_t, '2E75B6', sz=4)
for i, h in enumerate(['Assessment Type', 'When', 'Method', 'Target / Purpose']):
    header_cell(ass_t.rows[0].cells[i], h, '1F4E79', size=9)

ass_rows = [
    ('Pre-Assessment\n(Skill Audit)',
     'Before any training',
     '10-question scenario survey via LMS (self-reported skill level per tool)',
     'Establish baseline; guide track placement and skip options'),
    ('Formative Check-In',
     'Mid-module',
     'Scenario question or drag-and-drop activity built into LMS module',
     'Confirm understanding before learner attempts hands-on task'),
    ('Summative Demo',
     'End of each module',
     'Hands-on task with provided practice file; submitted via LMS for review',
     '≥80% of learners pass on first attempt'),
    ('30-Day Transfer Check',
     '30 days post-training',
     'Manager observation checklist + brief learner self-reflection survey',
     'Measure on-the-job behavior transfer'),
]
for ri, row_d in enumerate(ass_rows):
    row = ass_t.rows[ri + 1]
    bg = stripes[ri % 2]
    for ci, txt in enumerate(row_d):
        data_cell(row.cells[ci], txt, bg, bold=(ci == 0), size=9)

spacer(doc, 10)
heading(doc, 'Power User Competency Verification', level=2)
para(doc, (
    'Power Users must complete and submit all 12 module deliverables before attending the capstone. '
    'The capstone is a 4-hour live session: the candidate independently completes one realistic '
    'scenario task in each application (drawn from actual VMRC operations), then teaches one module '
    'to a small group of peers. The teach-back component confirms both skill mastery and the '
    'communication ability required for internal coaching.'
), pt_after=8)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 7: ROLLOUT TIMELINE & WHEN TO DEPLOY
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 7: Rollout Timeline & When to Deploy', level=1)

heading(doc, '7.1  The Evidence Behind the Timing', level=2)
para(doc, (
    'The single most common reason training programs fail is bad timing. Even the best-designed '
    'curriculum collapses when rolled out during a state survey, a winter staffing crisis, or the '
    'holiday season. For a retirement community, the organizational calendar has predictable '
    'high-pressure windows that must be avoided—and one clear “golden window” to capture every year.'
), pt_after=10)

cal_t = doc.add_table(rows=7, cols=3)
set_col_widths(cal_t, [1.2, 1.5, 4.05])
set_table_borders(cal_t, 'AAAAAA', sz=4)
for i, h in enumerate(['Period', 'Status', 'Reasoning']):
    header_cell(cal_t.rows[0].cells[i], h, '1F4E79', size=9)

cal_rows = [
    ('Jan–Feb',     'BEST WINDOW',       'EEF7EE', '37864B',
     'Post-holiday clarity. New-year mindset. Survey season not yet started. Staff back at full complement after holiday coverage gaps. Onboarding cycle restarts.'),
    ('Mar–May',     'CAUTION',            'FFFAEE', 'C55A11',
     'State survey season in Virginia (typically March–May). Operational attention shifts to compliance preparation. Launch only if survey is confirmed distant.'),
    ('Jun–Aug',     'AVOID FOR PILOTS',   'FFF8F0', 'C55A11',
     'Summer vacation coverage gaps and high CNA turnover season. Hard to maintain cohort continuity. Acceptable for asynchronous completions only.'),
    ('Sep–Oct',     'GOOD FOR PILOTS',    'EEF7EE', '37864B',
     'Ideal for Power User cohort pilot. Back-to-school energy, staff stable after summer, 90 days to refine materials before January full launch.'),
    ('Nov–Dec',     'DO NOT LAUNCH',      'FEE8E8', 'C00000',
     'Holiday season is the worst possible time. High emotional load, staffing crunch, resident family visits. Mandatory training creates resentment.'),
    ('Post-Survey\n(any)',  'OPPORTUNITY',     'EEF7EE', '37864B',
     'After a passed state survey, morale is high and leadership has credibility to invest in development. High-engagement bonus window—act quickly.'),
]
for ri, (period, status, bg, sc, reason) in enumerate(cal_rows):
    row = cal_t.rows[ri + 1]
    set_cell_bg(row.cells[0], bg)
    set_cell_bg(row.cells[1], bg)
    set_cell_bg(row.cells[2], bg)
    data_cell(row.cells[0], period, bg, bold=True, size=9)
    sc_rgb = RGBColor(int(sc[:2],16), int(sc[2:4],16), int(sc[4:],16))
    data_cell(row.cells[1], status, bg, bold=True, size=9, color=sc_rgb, center=True)
    data_cell(row.cells[2], reason, bg, size=9)

spacer(doc, 12)
heading(doc, '7.2  The 4-Phase Rollout Plan', level=2)

phases = [
    ('Phase 1: Power User Pilot',            'September–October',  '37864B',
     ['Recruit Power User cohort (4–8 volunteers across roles)',
      'Run all 12 modules with this cohort first',
      'Collect feedback, identify content gaps, refine materials',
      'Certify first cohort as Train-the-Trainer ready']),
    ('Phase 2: Administrative Staff Launch', 'January–February',   '2E75B6',
     ['Full launch for all administrative and office staff',
      'Instructor-led workshops held 2× per week in computer lab',
      'Power Users embedded in each session as peer coaches',
      'Weekly check-in meeting to monitor progress and resolve blockers']),
    ('Phase 3: Clinical Staff Rollout',      'February–March',     'C55A11',
     ['Asynchronous modules pushed to all nursing staff via LMS',
      'W1 mandatory for all; E1 for charge nurses; other modules voluntary/recommended',
      'Micro-workshops scheduled during mid-shift overlap windows',
      'Power Users available for drop-in support on each shift']),
    ('Phase 4: Evaluation & Certification',  'April–May',          '7F6000',
     ['Administer 30/60/90-day transfer assessments',
      'Review helpdesk ticket volume: pre vs. post training',
      'Issue Power User certifications and digital badges',
      'Publish iteration plan for Year 2 curriculum updates']),
]

for phase_name, dates, color_hex, items in phases:
    ph = doc.add_table(rows=1, cols=2)
    set_col_widths(ph, [3.5, 3.25])
    c0, c1 = ph.rows[0].cells[0], ph.rows[0].cells[1]
    set_cell_bg(c0, color_hex); set_cell_bg(c1, color_hex)
    p0 = c0.paragraphs[0]
    r0 = p0.add_run(phase_name)
    r0.font.bold = True; r0.font.color.rgb = WHITE; r0.font.size = Pt(11)
    p1 = c1.paragraphs[0]
    p1.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    r1 = p1.add_run(dates)
    r1.font.color.rgb = WHITE; r1.font.size = Pt(10)
    for item in items:
        bullet(doc, item, indent=0.3)
    spacer(doc, 8)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# SECTION 8: EVALUATION — KIRKPATRICK
# ──────────────────────────────────────────────────────────────
heading(doc, 'Section 8: Evaluation Plan — Kirkpatrick Model', level=1)
para(doc, (
    "The Kirkpatrick Four-Level Model is the gold standard for training evaluation. It moves beyond "
    "“did they finish it?” to ask “did it actually change anything?” "
    "Each level builds on the previous. For VMRC leadership to justify continued investment, "
    "you need data at all four levels."
), pt_after=10)

kirk_rows = [
    ('Level 1', 'Reaction',  '2E75B6',
     'Did staff find it useful and relevant?',
     'End-of-module survey (5 questions, 5-point scale) in LMS.\nTarget: ≥4.0/5.0 average satisfaction score.'),
    ('Level 2', 'Learning',  '37864B',
     'Did they actually acquire the skills?',
     'Module deliverable submission scores + performance checklist from instructor-led workshops.\nTarget: ≥80% of learners pass on first attempt.'),
    ('Level 3', 'Behavior',  'C55A11',
     'Are they using the skills on the job?',
     'Manager observation checklist at 30 and 60 days. Self-reported survey at 90 days. Helpdesk ticket volume tracking.\nTarget: 25% reduction in basic Office helpdesk tickets within 90 days.'),
    ('Level 4', 'Results',   '7F6000',
     'Did it move the needle for VMRC?',
     'Document quality audit (care plans pre/post). Time-on-task estimates for mail merge and pivot table work (manager-reported). Resident documentation compliance review.\nTarget: Measurable improvement in documentation consistency within 6 months.'),
]

for level, name, color_hex, question, method in kirk_rows:
    kt = doc.add_table(rows=1, cols=4)
    set_col_widths(kt, [0.7, 0.9, 1.8, 3.35])

    set_cell_bg(kt.rows[0].cells[0], color_hex)
    p = kt.rows[0].cells[0].paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(level); r.font.bold = True; r.font.color.rgb = WHITE; r.font.size = Pt(10)

    set_cell_bg(kt.rows[0].cells[1], 'F2F2F2')
    p = kt.rows[0].cells[1].paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run(name); r.font.bold = True; r.font.size = Pt(10)

    set_cell_bg(kt.rows[0].cells[2], 'FAFAFA')
    p = kt.rows[0].cells[2].paragraphs[0]
    r = p.add_run(question); r.font.italic = True; r.font.size = Pt(9)

    set_cell_bg(kt.rows[0].cells[3], 'FFFFFF')
    p = kt.rows[0].cells[3].paragraphs[0]
    r = p.add_run(method); r.font.size = Pt(9)

    spacer(doc, 8)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# APPENDIX A: SAMPLE JOB AIDS
# ──────────────────────────────────────────────────────────────
heading(doc, 'Appendix A: Sample Job Aid Layouts', level=1)
para(doc, (
    'Each module produces one laminated quick reference card. Below are abbreviated samples. '
    'Final cards are 8.5" × 5.5" half-sheets, color-coded by track, and distributed to workstations '
    'on the day of or immediately after the module session.'
), pt_after=10)

job_aids = [
    ('WORD QUICK REFERENCE  |  Styles & Templates', 'D6E4F0', NAVY, [
        ('Apply a style:',          'Click in paragraph → Styles pane → click style name'),
        ('Create new template:',    'File → Save As → Word Template (.dotx)'),
        ('Auto Table of Contents:', 'References tab → Table of Contents → Automatic Table 1'),
        ('Track Changes on/off:',   'Review tab → Track Changes (Ctrl+Shift+E)'),
        ('Accept all changes:',     'Review tab → Accept → Accept All Changes'),
    ]),
    ('EXCEL QUICK REFERENCE  |  Essential Functions', 'E2EFDA', GREEN, [
        ('IF statement:',   '=IF(condition, value_if_true, value_if_false)'),
        ('VLOOKUP:',        '=VLOOKUP(lookup_value, table_array, col_index, FALSE)'),
        ('SUMIF:',          '=SUMIF(range, criteria, sum_range)'),
        ('Pivot Table:',    'Insert tab → PivotTable → select range → OK'),
        ('Refresh Pivot:',  'Right-click pivot → Refresh  (or Alt+F5 for all pivots)'),
    ]),
    ('POWERPOINT QUICK REFERENCE  |  Design & Templates', 'FCE4D6', ORANGE, [
        ('Open Slide Master:',   'View tab → Slide Master'),
        ('Link Excel chart:',    'Copy in Excel → PPT: Paste Special → Paste Link → Excel Chart Object'),
        ('Presenter view:',      'Slide Show tab → Presenter View (with second monitor)'),
        ('Export to PDF:',       'File → Export → Create PDF/XPS → Publish'),
        ('Brand font rule:',     'Title: 40pt Calibri Bold  |  Body: 24pt Calibri  |  Caption: 18pt Calibri'),
    ]),
]

for title, bg, title_color, tips in job_aids:
    jt = doc.add_table(rows=1, cols=1)
    set_col_widths(jt, [6.75])
    set_cell_bg(jt.rows[0].cells[0], bg)
    p = jt.rows[0].cells[0].paragraphs[0]
    p.paragraph_format.left_indent = Inches(0.1)
    r = p.add_run(title)
    r.font.bold = True; r.font.size = Pt(11); r.font.color.rgb = title_color
    for lbl, val in tips:
        tp = doc.add_paragraph()
        tp.paragraph_format.left_indent = Inches(0.25)
        tp.paragraph_format.space_after = Pt(3)
        r1 = tp.add_run(lbl + '  ')
        r1.font.bold = True; r1.font.size = Pt(10); r1.font.color.rgb = title_color
        r2 = tp.add_run(val)
        r2.font.size = Pt(10)
    spacer(doc, 10)

doc.add_page_break()

# ──────────────────────────────────────────────────────────────
# APPENDIX B: DESIGNER'S RATIONALE
# ──────────────────────────────────────────────────────────────
heading(doc, "Appendix B: Designer’s Rationale", level=1)
para(doc, (
    'This section explains the instructional design decisions behind this curriculum and how they connect '
    'to the designer’s professional background. It is intended for leadership and peer review.'
), pt_after=10)

rationale = [
    ('CTT+ Certification (CompTIA Certified Technical Trainer)',
     'The modular structure, Bloom’s-aligned objectives, and blended delivery model reflect formal '
     'instructional design training. The CTT+ framework directly informed the formative/summative '
     'assessment split and the emphasis on performance-based demonstration over multiple-choice testing.'),
    ('MOUS Master (Microsoft Office User Specialist)',
     'Content accuracy in all 12 modules—the function selection in Excel, the Track Changes workflow '
     'in Word, the Master Slide architecture in PowerPoint—draws from MOUS-level Microsoft Office '
     'expertise. These are not generic tutorials; they are precision-crafted skill progressions.'),
    ('Valley Vocational Technical Center (2008–2014)',
     'Six years designing and delivering hands-on technical curriculum for students and adult learners '
     'directly informed the role-differentiation strategy. The CNA track vs. Administrator track split '
     'mirrors the vocational approach of meeting learners at their actual skill level.'),
    ('Wellness Concepts — Healthcare Operations (2018–2025)',
     'Seven years inside a healthcare operation—including IDT meeting participation—gives this '
     'curriculum operational credibility. The scenario examples are drawn from real workflow pain points '
     'observed in a senior living environment, not textbook abstractions.'),
    ('LearnWorlds Platform Creator Certification',
     'The LMS delivery architecture in Section 5 is based on direct experience building and deploying '
     'courses in LearnWorlds. Recommendations for SCORM export, manager dashboard, and mobile-first '
     'module design are platform-informed, not theoretical.'),
]

for credential, rationale_text in rationale:
    p = doc.add_paragraph()
    p.paragraph_format.space_after = Pt(2)
    r = p.add_run(credential)
    r.font.bold = True; r.font.color.rgb = NAVY; r.font.size = Pt(11)
    para(doc, rationale_text, size=10, indent=0.3, pt_after=10)

spacer(doc, 12)

# Final signoff bar
sign = doc.add_table(rows=2, cols=1)
set_col_widths(sign, [6.75])
set_cell_bg(sign.rows[0].cells[0], '1F4E79')
p = sign.rows[0].cells[0].paragraphs[0]
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run('Michael Cirigliano, CTT+  |  MOUS Master  |  IT Applications Administrator')
r.font.bold = True; r.font.color.rgb = WHITE; r.font.size = Pt(11)

set_cell_bg(sign.rows[1].cells[0], '2E75B6')
p = sign.rows[1].cells[0].paragraphs[0]
p.alignment = WD_ALIGN_PARAGRAPH.CENTER
r = p.add_run('Virginia Mennonite Retirement Community  |  Harrisonburg, VA  |  tykecirigliano@gmail.com')
r.font.color.rgb = RGBColor(0xD6, 0xE4, 0xF0); r.font.size = Pt(10)

# ──────────────────────────────────────────────────────────────
# FOOTER (page numbers)
# ──────────────────────────────────────────────────────────────
for section in doc.sections:
    footer = section.footer
    fp = footer.paragraphs[0]
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fp.clear()
    r1 = fp.add_run('VMRC Microsoft Office Power User Training  |  ID Curriculum  |  Page ')
    r1.font.size = Pt(8); r1.font.color.rgb = GRAY
    r2 = fp.add_run()
    r2.font.size = Pt(8); r2.font.color.rgb = GRAY
    add_page_number_field(r2)

# ──────────────────────────────────────────────────────────────
# SAVE
# ──────────────────────────────────────────────────────────────
output = r'C:\Users\tykec\Desktop\1BigFolderTrueDesktop\Instructional Design\VMRC_MS_Office_Power_User_Curriculum.docx'
doc.save(output)
print(f'Saved: {output}')
